# version: '3.8'  # optional: can delete this

services:

  nginx:
     build: ./requirements/nginx
     container_name: nginx
     ports:
       - "443:443"
     volumes:
       - wordpress_data:/var/www/html
       - certs:/etc/ssl/private
     networks:
       - inception
     depends_on:
       - wordpress
     restart: always

  wordpress:
     build: ./requirements/wordpress
     container_name: wordpress
     volumes:
       - wordpress_data:/var/www/html
     environment:
       - DOMAIN_NAME=${DOMAIN_NAME}
       - MYSQL_DATABASE=${MYSQL_DATABASE}
       - MYSQL_USER=${MYSQL_USER}
       - MYSQL_PASSWORD=${MYSQL_PASSWORD}
       - MYSQL_HOST=mariadb
       - WP_ADMIN_USER=${WP_ADMIN_USER}
       - WP_ADMIN_PASS=${WP_ADMIN_PASS}
       - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
       - WP_USER=${WP_USER}
       - WP_USER_PASS=${WP_USER_PASS}
     networks:
       - inception
     depends_on:
        - mariadb
     restart: always

  mariadb:
     build: ./requirements/mariadb
     container_name: mariadb
     volumes:
       - mariadb_data:/var/lib/mysql
     environment:
       - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
       - MYSQL_DATABASE=${MYSQL_DATABASE}
       - MYSQL_USER=${MYSQL_USER}
       - MYSQL_PASSWORD=${MYSQL_PASSWORD}
     networks:
       - inception
     restart: always

volumes:
  wordpress_data:
    driver_opts:
      type: none
      o: bind
      device: /home/abderahim/data/wordpress

  mariadb_data:
     driver_opts:
       type: none
       o: bind
       device: /home/abderahim/data/mariadb

  certs:
    driver_opts:
      type: none
      o: bind
      device: /home/abderahim/data/certs


networks:
  inception:
    driver: bridge

